### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by evansiroky**
Refactor app to be more intuitive and simple.

### CODE REVIEW

**Comment by evansiroky** [comment]
@trevorgerhardt when you get time, let me know if this code is looking like it's on the right track.

**Review by trevorgerhardt — COMMENTED** [review]
Lot's of code removed. Is this in a state that can be set up and run locally?

**Comment by evansiroky** [comment]
Yes, it can be run locally.  It requires a running instance of r5 using the r5 branch `isochrone-endpoint`.  I can private message you the config I have for `env.yml`.

**Comment by evansiroky** [comment]
@trevorgerhardt how is the review coming along?  I've made a lot of changes since this PR.  Should I merge in those changes to this PR and you can review from there?

**Comment by trevorgerhardt** [comment]
@evansiroky go ahead and merge those changes in, I let this get away from me and never got it running locally. Will get it running and review tomorrow 👌

**Comment by evansiroky** [comment]
@trevorgerhardt when you get a chance, please review.  I merged in all the work I've been doing into this PR.

**Comment by evansiroky** [comment]
Here's a summary of the PR.

I have shifted away from the concept of disagreggating commuters from sites and analyses.  Now, commuters must be added to specific sites and analyses happen automatically at sites.  Also, I have added the concept of multi-site analyses.

Summary of changes:

## Client

### Tests

* Modified the commuter and site actions/reducers tests and added tests for polygon actions/reducers
* Preserved only a few container / component tests that got reused in the refactor
* No tests for detailed rendering of site stuff
* No tests yet for multi-site stuff
* Consolidated util tests

### Actions / Reducers

* Got rid of Agencies, Organizations, Groups and Analyses.
* Refactored Commuter and Site to follow new paradigm
* Added Polygon action/reducer in order to lazy-load polygon data that has been calculated for sites.

### Containers / Components

* Got rid of views associated with Agencies, Organizations, Groups and Analyses
* Refactored Site view to show commuters, isochrones and ridematching
* Added Multi-site Container which re-uses most functionality in Site view
* Added some map helpers including a map Legend and Marker-clusterer
* Added some button and field helpers (back-button, button-link, fieldgroup)
* User-home is the new landing page upon login (it used to be Agencies)

### Utils

* Consolidated the files common, components, table and ui into a single index.js file

## package.json

### Additions

**lodash.uniqueid** - for something with leaflet mocking
**@conveyal/lonlat** - used in client
**@turf/distance, @turf/helpers, jsts** - for calculating isochrone polygons in the browser
**@turf/inside** - for doing server-side calculation of travel times
**colorvert** - for shading isochrones
**debounce** - for debouncing fetch errors
**leaflet.markercluster** - for ridematching visualization
**invariant** - used in button-link (copied from react-router)
**react-leaflet-heatmap-layer** - for showing ridematching heatmap

### Removals

**react-leaflet-cluster-layer** - replaced by leaflet.markercluster
**react-vis** - removed since no longer using in analysis

## Server

* Added Auth0 handling
* Removed agency, analysis, group, organization, trip models and api endpoints
* Added hook on commuter model so that commuter travel times get recalculated upon save
* Added hook on site to perform isochrone analysis upon save or location change
* Geocoding plugin
  * Switch to retries with exponential delay for handling error responses from server
  * Added option to define a postGeocode hook for extra calculations on model after geocode has finished
  * Add temporary hack to correct address searches in Washington, DC
* Added multi-site, polygon models and api endpoints
* Removed trip planning util with isochrone travel time util for calculating travel times of commuters
* Made rest endpoints jwt friendly and added Collection DELETE endpoint

**Comment by trevorgerhardt** [comment]
@evansiroky after clicking through the deployed app and reading through enough changes to get a rough feel for the PR I'd say this is good to merge and would recommend doing that ASAP. A few comments for work going forward:

1. Major read flag that a single file (`client/component/site.js`) has 1385 lines making up over 1/3rd of the client code (by line count). I would prioritize refactoring that in the near future.
2. I would make a broad recommendation not to rely on Bootstrap or Bootstrap related JavaScript libraries, the bundle size of `react-bootstrap` and `react-bootstrap-table` and the lock in it causes just don't seem worth it to me. It's a decent CSS library that can be applied with classes or easily with simple custom components.
3. Remember that every feature, no matter how small, is another place for things to break. The more you can remove, the better. Features I would designate for immediate removal:
    1. Any drag and drop
    2. Breadcrumb bar (application is super simple)
    3. Map style selection (we can't settle on one?)
    4. Custom sliders (`<input type=range />` should be fine)
4. Don't use two libraries when you can use one. `react-widgets` is 5.2% of the commute bundle size and the Combobox (only component used from there that I could tell) has the same functionality of `react-select`, which we already use extensively across our code bases.

Also, I don't have specific recommendations but would like to take a shot at improving the general look and feel of this application after this PR is merged.

**Review by trevorgerhardt — APPROVED** [review]

**Comment by evansiroky** [comment]
Thanks for the review!  I'm going to great issues for each of your major points.

**Pull request merged**
